version: "3.8"
services:
  hibernate_batch_mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe
    ports:
      - "3306:3306"